version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.10  # Official CircleCI Node.js image
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Save dependencies to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

workflows:
  build_and_test:
    jobs:
      - build
